### ISSUE TITLE
Skeleton conjure false positive

### ISSUE THREAD

**Issue by misfit-sculler** [NadyaNayme/NyusNecroJobGauge#3]
When the zombie is conjured, both zombie and skeleton buff trackers are active and count down with the same duration values.

**Comment by misfit-sculler** [comment]
Skeleton conjured
![image](https://github.com/NadyaNayme/NyusNecroJobGauge/assets/157226282/95ff8d68-255e-45aa-916e-554d7529a2a1)

Zombie conjured - 
![image](https://github.com/NadyaNayme/NyusNecroJobGauge/assets/157226282/6f36222b-9b8e-4eda-8406-f2c5fe6b91e0)

Zombie then skeleton
![image](https://github.com/NadyaNayme/NyusNecroJobGauge/assets/157226282/de2cbc7c-9a76-4c9a-bce2-580dd1aa9c11)

Skeleton then zombie
![image](https://github.com/NadyaNayme/NyusNecroJobGauge/assets/157226282/37ae361d-3b4e-4304-9e5f-49bae2bb8947)

**Comment by misfit-sculler** [comment]
It seems like there's some logic that considers the skeleton as summoned whenever the zombie is summoned.

**Comment by NadyaNayme** [comment]
Not any special logic just bad thresholds for the matching. What's probably happening is enough of the purple gradient is causing a match.

I've noticed this bug myself a few times but never really had the time to dig into what was happening. The order of the buffs causing the issue absolutely makes sense and I should be able to address it + get the issue fixed by tweaking the thresholds a bit more.

Thanks for the report!

**Comment by misfit-sculler** [comment]
Accidentally closed the ticket - reopening!

I just wanted to say thanks for making this tool! I was finally able to get the reaper title, with a huge part being due to this buff tracker.

**Comment by misfit-sculler** [comment]
Hi @NadyaNayme, could you point me to where the thresholds that need to be tuned are? I can see if I can find ones that work for me.

**Comment by NadyaNayme** [comment]
Sure thing - it's the numbers in this for loop: 
- https://github.com/NadyaNayme/NyusNecroJobGauge/blob/main/src/index.ts#L1013C1-L1033C4

The numbers should be raised (require more matching pixels) and not lowered. I'd recommend 5-step (70->75->80->85) or 10-step (70->80->90) intervals. One of those things that wouldn't take me too long to fix but also just haven't had the time. :(

If I had to throw a random guess into the dark the thresholds can probably be increased to 280-300 seeing as they are opaque buffs (no transparency) that means nearly 100% of the pixels should match. Zombie has 325 pixels so increasing its threshold to 280-300 would probably do the trick.

**Comment by misfit-sculler** [comment]
Thanks! I haven't done extensive testing to figure out the upper and lower bounds of this threshold, but setting the skeleton to 150 has been working well for me. 280 without stacks works great, but once you start building stacks the matching is inconsistent.

**Comment by NadyaNayme** [comment]
Ah right, 280 was the upper bounds of the pixels. The timer and font will account for some lost pixels due to the white/black pixels of the font. Conservative amount is -30~ so a threshold of 220-250 should be good. 

But if you're saying 150 has been without issues I can push it up to 150. :) Really the threshold just has to be however high enough to prevent false positives. Except when we're getting false positives there's not really any difference between low and high threshold matches - 150 is every bit as good as 200 if neither have false positives.

**Comment by NadyaNayme** [comment]
I've bumped the thresholds to 150 which should hopefully fix this issue for everyone. Thanks for testing thresholds!
